### ISSUE TITLE
"export 'default' (reexported as 'normalize') was not found in './helpers/normalizeText'

### ISSUE THREAD

**Issue by hadarbmdev** [react-native-training/react-native-elements#1780]
I'm using:
   "react-native": "0.55.x",
    "react-native-elements": "^1.0.0",
    "react-native-vector-icons": "^6.3.0",
    "react-native-web": "^0.9.x",

Installed via NPM.

Trying to use Button:
import { Button } from 'react-native-elements'
<Button >Register</Button>

**Expected behaviour**
Project should compile.

**Describe the bug**
Getting this error message:
./node_modules/react-native-elements/src/index.js
"export 'default' (reexported as 'normalize') was not found in './helpers/normalizeText'

**Comment by iRoachie** [comment]
Are you using with react-native-web? Did you follow the walkthrough on https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html

**Comment by writzx** [comment]
I have used CRA to create a web-only app and when using `react-native-elements` latest version I get the same error. Earlier I had a similar project setup which used to work without a hitch using the same setup and same components from `react-native-elements`. Right now I am only using `Input` and getting this error.

**Comment by writzx** [comment]
as a workaround, change the line `module.exports = normalize` to `export default normalize`

**Comment by thorakmedichi** [comment]
> as a workaround, change the line in:
> `./node_modules/react-native-elements/src/helpers/normalizeText`
> from: `module.exports = normalize`
> to: `export default normalize`

This is a bad idea as any update will overwrite this change in the core package. If someone is doing this please note you need to lock this package version.

This is not a long term solution unfortunately.

**Comment by thorakmedichi** [comment]
> Are you using with react-native-web? Did you follow the walkthrough on https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html

I did use that guide for my setup @iRoachie. One thing to note is that I did not do `yarn add react-native-elements@beta` as I noticed you transitioned to 1.0.0. When that article was written I believe you were on 0.19.0 or some earlier version and `beta` was for the 1.0.0 release.

Is this incorrect thinking? Is there still a beta branch that is different than 1.0.0?

**Comment by writzx** [comment]
> > as a workaround, change the line in:
> > `./node_modules/react-native-elements/src/helpers/normalizeText`
> > from: `module.exports = normalize`
> > to: `export default normalize`
> 
> This is a bad idea as any update will overwrite this change in the core package. If someone is doing this please note you need to lock this package version.
> 
> This is not a long term solution unfortunately.

That is why its a "workaround". Also I want to point out. if for some reason `node_modules` is deleted (i need to do this a lot of times) the changes need to be made again.

One thing I have noticed is that `beta 7` didn't have this issue which I had used in my old project. Only in the 1.0.0 stable branch this is happening now (didn't test beta branch if there is any). [At first I suspected webpack to be the problem but downgrading webpack doesn't solve it]

**Comment by LeHaine** [comment]
Make sure you are adding this to your webpack file where you process JS with Babel.

```
include: [
  paths.appSrc,
  `${paths.appNodeModules}/react-native-elements`,
  `${paths.appNodeModules}/react-native-vector-icons`
]
```

**Comment by thorakmedichi** [comment]
> Make sure you are adding this to your webpack file where you process JS with Babel.
> 
> ```
> include: [
>   paths.appSrc,
>   `${paths.appNodeModules}/react-native-elements`,
>   `${paths.appNodeModules}/react-native-vector-icons`
> ]
> ```

Yeah I have that in my webpack file already.

**Comment by thorakmedichi** [comment]
I just wanted to leave an update. I have now gone back and done `yarn add react-native-elements@beta` so now I see `"react-native-elements": "^1.0.0-beta8"` instead of `"react-native-elements": "^1.0.0"` in my package json

now I get this error again
```
Failed to compile.

./node_modules/react-native-ratings/src/SwipeRating.js
SyntaxError: /home/thorakmedichi/Development/Projects/stormfree/day-tracer/node_modules/react-native-ratings/src/SwipeRating.js: Support for the experimental syntax 'classProperties' isn't currently enabled (41:23):

  39 |
  40 | export default class SwipeRating extends Component {
> 41 |   static defaultProps = {
     |                       ^
  42 |     type: 'star',
  43 |     ratingImage: require('./images/star.png'),
  44 |     ratingColor: '#f1c40f',

```

**Comment by iRoachie** [comment]
Why are you using the beta still?

**Comment by thorakmedichi** [comment]
> Why are you using the beta still?

Because that is what the blog article says to use... so I just went back and followed it line by line again. 
https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html

I posed the question earlier in here whether using 1.0.0 was valid or if I needed @beta and no one answered. So I just assumed I HAD to use the beta. 

Then I fixed the missing info in the webpack that the blog didn't have for the `star` error by adding `${paths.appNodeModules}/react-native-ratings`. And because I use react-navigation I had to add ``${paths.appNodeModules}/react-native-status-bar-height``

**Comment by hadarbmdev** [comment]
@thorakmedichi Thanks, I'll try once I get back to the UI task again.

**Comment by thorakmedichi** [comment]
Nothing I am trying will display those icons. Even with the new webpack settings and using v1.0.0 OR v1.0.0-beta8.

Does anyone have any other ideas?

**Comment by writzx** [comment]
Please update to the latest version (1.1.0) of the library. This issue has already been fixed.

**Comment by thorakmedichi** [comment]
> Please update to the latest version (1.1.0) of the library. This issue has already been fixed.

Updated to 1.1.0 and still having this issue of icons not rendering. Everything else seems fine like Button, Image, Rating etc. However anything dealing with icons either shows an empty box (like beside "Timeline" and "Calendar" text or it shows a ? like in the button

![screenshot_20190306_121624](https://user-images.githubusercontent.com/5092843/53910878-d097bf80-4009-11e9-8e97-f588ae4b21b8.png)

**Comment by writzx** [comment]
Try using the font files in the `dist` directory of rnvi. 
`import Icon from 'react-native-vector-icons/dist/MaterialIcons' `.


Also check your logs there should be some info about why its not showing up.

**Comment by thorakmedichi** [comment]
> Try using the font files in the `dist` directory of rnvi.
> `import Icon from 'react-native-vector-icons/dist/MaterialIcons' `.
> 
> Also check your logs there should be some info about why its not showing up.
> 
> Also are you using a default font set in the main html document?

No change with `import Icon from 'react-native-vector-icons/dist/MaterialIcons'`.

Any particular log I should look at? I mean the yarn build is successful with no errors. Nothing obvious seems to be showing up. Just wont display the logo. Linting and unit tests passing.

This is my index.html
```
<!DOCTYPE html>
<html lang="en"  style="height: 100%">
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000000">

    <title>DayTracer</title>
  </head>
  <body style="height: 100%">
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <div id="root" style="height: 100%"></div>
  </body>
</html>

```

**Comment by haruelrovix** [comment]
@thorakmedichi Do you have the repo (with minimal code to reproduce the issue) that can you share? Seems your problem isn't with RNE anymore but RNVI.

**Comment by thorakmedichi** [comment]
> @thorakmedichi Do you have the repo (with minimal code to reproduce the issue) that can you share? Seems your problem isn't with RNE anymore but RNVI.

Hey @haruelrovix I created a super stripped down version of our project, trying to keep all the same basic setup with redux etc in place. But it just renders a single screen with a sidebar and footer component with the Icon's in there that dont work for us.

https://github.com/thorakmedichi/rnw-sample

**Comment by haruelrovix** [comment]
@thorakmedichi 

- missing `type`
- wrong import for icon

here is the [fixes](https://github.com/thorakmedichi/rnw-sample/pull/2)

![image](https://user-images.githubusercontent.com/17120764/54806122-adc50680-4cab-11e9-877f-4523ad18e728.png)

🤝

**Comment by thorakmedichi** [comment]
> @thorakmedichi
> 
>     * missing `type`
> 
>     * wrong import for icon
> 
> 
> here is the [fixes](https://github.com/thorakmedichi/rnw-sample/pull/2)
> 
> ![image](https://user-images.githubusercontent.com/17120764/54806122-adc50680-4cab-11e9-877f-4523ad18e728.png)
> 
> handshake

Oh man... so awesome. Such a huge help. Thank you ever so much

**Comment by thorakmedichi** [comment]
This can be marked closed now if you like. I have all issues resolved now.

**Comment by yuxiaomin** [comment]
> Please update to the latest version (1.1.0) of the library. This issue has already been fixed.

I still get the error even I update to the latest version 1.1.0

**Comment by iRoachie** [comment]
Trying clearing your node_modules and metro-bundler cache. The problem doesn’t exist anymore
