### ISSUE TITLE
[Avatar] icon -> type prop should default to 'material', not 'font-awesome'

### ISSUE THREAD

**Issue by joncursi** [react-native-training/react-native-elements#304]
Every other component that uses `<Icon />`, [including the `<Icon />` component itself](https://react-native-training.github.io/react-native-elements/API/icons/), uses `material` as the default icon library if no `type` is specified. Avatar should be no different.

See: https://github.com/react-native-training/react-native-elements/blob/master/src/avatar/Avatar.js#L100

**Comment by Monte9** [comment]
@joncursi that's a good point. Will update this in the next release.

**Comment by bozzmob** [comment]
Thanks @Monte9 for the fix.

**Comment by Monte9** [comment]
This is fixed with `v0.11.2`

**Comment by gsklee** [comment]
@Monte9 You may wanna update the docs as well, it's still showing examples using Font Awesome icons: https://react-native-training.github.io/react-native-elements/API/avatar/

**Comment by Monte9** [comment]
@gsklee good catch. Will do so soon. Thanks.

**Comment by Monte9** [comment]
Updated the docs here: https://github.com/react-native-training/react-native-elements/pull/438/commits/68261c1b03bace071e5abbd485cd76ae651008ba
