### ISSUE TITLE
Button with borderRadius feedback ripple issue

### ISSUE THREAD

**Issue by simonasdev** [react-native-training/react-native-elements#328]
### Description

1. Added a button with borderRadius
2. Expected feedback ripples to be contained within the button
3. Feedback ripples go past the button to its (internal) parent container, which doesn't have borderRadius. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6169923/25294203/cdfd887e-26e6-11e7-8be1-785c5aaad98f.gif)
`react-native-elements` version 0.11.1.

### Reproduction Steps and Sample Code
```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
//... skipped for brevity
import { Button } from 'react-native-elements';

export default class DoctorItem extends Component {

  renderSubtitle () {
    const { doctor, onPress } = this.props

    return (
      <View style={styles.subtitle}>
        <Text style={styles.grey}>{doctor.phone}</Text>
        <View style={styles.rightTitle}>
          <Text style={styles.grey}>Artimiausias laikas 13:00</Text>
          <Button
            title='Registruotis'
            onPress={onPress}
            buttonStyle={styles.button}
          />
        </View>
      </View>
    )
  }

  render () {
    const { doctor, onPress } = this.props

    return (
      <ListItem
        roundAvatar
        key={doctor.id}
        title={doctor.full_name}
        subtitle={this.renderSubtitle()}
        avatar={{uri: doctor.photo && doctor.photo.thumb_url || AppConfig.defaultDoctorImageUrl}}
        hideChevron={true}
      />
    )
  }
}

const styles = StyleSheet.create({
  subtitle: {
    flex: 1,
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingLeft: 10,
    paddingTop: 5,
  },
  button: {
    margin: 5,
    borderRadius: 30,
  },
  rightTitle: {
    justifyContent: 'center',
  },
})
```

### Solution
Wrapping Button in another View with borderRadius doesn't change anything, which suggests that problem lies in the Button component.
Probably the internal wrapping container needs to respect the borderRadius of the Button (TouchableNativeFeedback/TouchableWithoutFeedback?) itself.

I'd be happy with a dirty fix, if possible. Let me know if you need any more information.

**Comment by binoy14** [comment]
@simonasdev This sounds similar to the thread in #193 
Does this comment help https://github.com/react-native-training/react-native-elements/issues/193#issuecomment-282225999 ?

**Comment by Monte9** [comment]
@simonasdev you are right! The borderRadius is not being applied on the parent component of the button view. I think we should change this to expose a `containerViewStyle` that let's you add the borderRadius on it. 
In the meantime can you try this:
``` js
<Button
  title='Registruotis'
  onPress={onPress}
  buttonStyle={styles.button}
 style={{borderRadius: "30"}}
/>
```

**Comment by simonasdev** [comment]
@binoy14 it would help, because this is exactly how rounded TouchableNativeFeedback should be implemented. But what I don't understand is why when I write them seperately, i.e.:
```
<View style={{borderRadius: 24, backgroundColor: AppColors.brand.primary, flex: 1}}>
  <TouchableNativeFeedback background={TouchableNativeFeedback.Ripple('ThemeAttrAndroid', true)}>
    <View style={[AppStyles.flex1, {alignItems: 'center', justifyContent: 'center'}]}><Text>Sveiki</Text></View>
  </TouchableNativeFeedback>
</View>
```
it works. But when I wrap the `Button` with the same `View`, it doesn't even get rounded :D
```
<View style={{borderRadius: 24, flex: 1}}>
  <Button
    title={'Login'}
    icon={{ name: 'lock' }}
    onPress={null && Actions.login}
    attributes={{background: TouchableNativeFeedback.Ripple('ThemeAttrAndroid', true)}}
  />
</View>
```
![image](https://cloud.githubusercontent.com/assets/6169923/25316590/8a598a40-2872-11e7-82b9-a29c0fc1940a.png)
Even though the `Button` component just renders the TouchableNativeFeedback, so my guess is the result should be the same. Can you tell what is causing this?

@Monte9 I looked at the source in Button.js and looked at the structure of this component, and saw that style prop isn't used at all. The point is, I believe, that when borderRadius is passed as a prop and the `Platform.os === "android"'`, the returning `Component` should be wrapped around a `View`, to which style prop would be `style={{borderRadius: this.props.borderRadius}}`

**Comment by Monte9** [comment]
@simonasdev you are right, it's not being used right now, but I assumed that the `...` operator would apply this. But apparently not. 

> I think we should change this to expose a containerViewStyle that let's you add the borderRadius on it.

I am going to slate this for `v0.11.3`release (in a week or so) as I would like to test it before it's released. 

Feel free to submit a PR for this if you have time.

**Comment by simonasdev** [comment]
Ah, @Monte9 you probably are correct about the ...attributes variable, but the problem is that TouchableNativeFeedback doesn't have a borderRadius prop or style for borderRadius. I'll probably have time this week. So you suggest always wrapping the returned `Component` in a `View`, and applying styles to it based on `containerViewStyle` prop?

**Comment by binoy14** [comment]
@simonasdev I am curious to see if you use the Button component from react native does that have same effect. 

`import { Button } from 'react-native'`

**Comment by simonasdev** [comment]
@binoy14 I've just tried it, and it behaves the same as react-native-elements button - wrapping `View` with borderRadius around it has no effect and the component itself has no borderRadius or style prop at all, so no way to customize it.
Also, I just discovered another bug (most likely unrelated) that pressing on text or the icon of the button produces the ripple centered from top-left corner, while pressing anywhere else on the button produces the correct ripple. `Button` from react-native though, produces the correct ripple regardless of where the press happens. I'll probably submit a different issue for it.

**Comment by Monte9** [comment]
> So you suggest always wrapping the returned Component in a View, and applying styles to it based on containerViewStyle prop?
yes. 

> I'll probably have time this week. 
Awesome! I'll keep an eye out for the PR.

**Comment by tarang9211** [comment]
@Monte9 just to avoid duplicate PR's, who's getting this one?

**Comment by simonasdev** [comment]
So I've tried to hack something up and managed [to make it work](https://github.com/simonasdev/react-native-elements/commits/round-button-feedback) for my use case, but this change definitely breaks behaviour. For example, if borderRadius and raised are passed in as props, there is a weird rectangular outline (if borderRadius wasn't passed in `containerViewStyle` prop), since I had to move some styles from `View` contained in the `Component` to the wrapping `View`, to make it look as it did before the change.

Also, there are 15 failed tests because of unmatching snapshots, 'Method “props” is only meant to be run on a single node. 2 found instead' (something from ShallowWrapper.single) and `should have onPress event` tests fail with 'Expected mock function to have been called.' I don't know how should I fix these and don't really have resources to investigate further.
I could submit the PR as it is now, and you could work from there, or you can just use the code from the link above. What are your thoughts on this?

**Comment by binoy14** [comment]
@simonasdev Can you at least make a PR to next branch and let's try to investigate what's going on

**Comment by binoy14** [comment]
This has been fixed and will be released as part of `0.12.0`

**Comment by doniyor2109** [comment]
When I set ```borderRadius``` in  ```containerViewStyle``` it works, however my previously set box shadow is not working as expected. ```borderRadius``` slices the box shadow

**Comment by Kleinhummel** [comment]
I am still experiencing this issue on Android.

**Code:**
`<Button title="Edit" buttonStyle={{ borderRadius: 50 }} icon={{ name: 'edit', color: 'white' }}></Button>`

**Versions:**
- "react": "16.9.0"
- "react-native": "0.61.4"
- "react-native-elements": "1.2.7"

**Image:**
![Button](https://user-images.githubusercontent.com/47432229/74058309-08f80880-49e6-11ea-8f42-8adaf571ec83.png)
