### ISSUE TITLE
ListItem：Unrecognized font family 'Material Icons'

### ISSUE THREAD

**Issue by wuyunqiang** [react-native-training/react-native-elements#503]
### Description

1. Explain what you did

code:
 <List containerStyle={{ marginBottom: 20 }}>
          {
                      list.map((l, i) => (
                        <ListItem
                          roundAvatar
                          onPress={() => console.log('Pressed')}
                          avatar={l.avatar_url}
                          key={i}
                          title={l.name}
                          subtitle={l.subtitle}
                          rightTitle={'right'}
                        />
                      ))
                  }
        </List>

2. What you expected to happen
android:
<img width="368" alt="androidright" src="https://user-images.githubusercontent.com/13480948/28258953-81cc7046-6b06-11e7-88c8-872d290ebee9.png">
ios:
<img width="414" alt="iosright" src="https://user-images.githubusercontent.com/13480948/28258930-67c0c850-6b06-11e7-9c5f-baf9d4762b45.png">

3. What actually happens
android:
<img width="368" alt="androidlistitem" src="https://user-images.githubusercontent.com/13480948/28258886-276021c0-6b06-11e7-85a3-b91411d0bde8.png">
ios:
<img width="414" alt="ioslistitem" src="https://user-images.githubusercontent.com/13480948/28258900-3960ab06-6b06-11e7-9949-c2a5b2e120c9.png">

"react": "16.0.0-alpha.6",
"react-native": "0.44.3",
"react-native-elements": "^0.14.0",
"react-native-vector-icons": "^4.2.0",

### Solution
I set  hideChevron: false.

**Comment by iRoachie** [comment]
@wuyunqiang We use `react-native-vector-icons` under the hood for showing icons. Did you link the library at setup?

`react-native link react-native-vector-icons`

**Comment by wuyunqiang** [comment]
@iRoachie  yes I link.
I used  react-native-vector-icons for tab.

**Comment by binoy14** [comment]
@wuyunqiang What version of react-native-vector-icons are you using?

**Comment by wuyunqiang** [comment]
@binoy14 
"react-native-vector-icons": "^4.2.0",

**Comment by binoy14** [comment]
@wuyunqiang did you try removing node_modules and reinstalling it? Could you also provide the code your using causing this issue and finally try using snack.expo.io to check if you can reproduce this bug there.

**Comment by myerzman** [comment]
I have the same issue. How do I reinstall node_modules?

**Comment by xavier-villelegier** [comment]
@myerzman `rm -rf node_modules && npm i`

**Comment by k4ch0w** [comment]
I'm also experiencing this issue, I just recently fresh installed my machine. It happens when using any Icon component. 

`node -v
v8.2.1`

package.json
```{
  "name": "",
  "version": "0.0.1",
  "description": "hot sauce",
  "author": "",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^18.0.4",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-native-elements": "^0.14.0",
    "react-native-modal": "^2.4.0",
    "react-native-sortable-listview": "^0.2.2",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.1",
    "redux-persist": "^5.0.0-proto.6",
    "redux-thunk": "^2.2.0"
  }
}
```

I also ran 
`npm i react-native-vector-icons --save && react-native link react-native-vector-icon`

I am receiving this error on IOS. 

I tried to import expos icons as a workaround

```import { MaterialIcons } from '@expo/vector-icons';
...
 componentWillMount() {
     await Font.loadAsync(MaterialIcons.font);
  }
```
It still gave me the same error. 

Here is the error
<img width="321" alt="screen shot 2017-08-01 at 4 52 12 am" src="https://user-images.githubusercontent.com/25095513/28824048-39502450-7675-11e7-8c98-d432eaa3f5cf.png">

**Comment by xavier-villelegier** [comment]
@k4ch0w Using `expo` you shouldn't have to link any libraries (that is the strength of `expo`).
You shouldn't render anything since the font is not loaded, so you have to update a `isLoaded` state in order to know when you can render anything.

Have a look at this example https://github.com/react-native-training/react-native-elements/issues/490#issuecomment-318164502

You can also read this part of the Expo documentation https://docs.expo.io/versions/v19.0.0/guides/preloading-and-caching-assets.html

**Comment by Monte9** [comment]
@k4ch0w please see @xavier-villelegier's answer above. When using Expo, the fonts need to be loaded first before you can render anything.

**Comment by k4ch0w** [comment]
@xavier-villelegier Thanks Xavier! That fixed it for me.

**Comment by ji3000** [comment]
Need to link fonts into your project. This worked for me. 

Source:
If you want to use any of the bundled icons, you need to add the icon fonts to your Xcode project. Just follow these steps:

Browse to node_modules/react-native-vector-icons and drag the folder Fonts (or just the ones you want) to your project in Xcode. Make sure your app is checked under "Add to targets" and that "Create groups" is checked if you add the whole folder.
Edit Info.plist and add a property called Fonts provided by application (or UIAppFonts if Xcode won't autocomplete/not using Xcode) and type in the files you just added. It will look something like this:
XCode screenshot

Note: you need to recompile your project after adding new fonts, also ensure that they also appear under Copy Bundle Resources in Build Phases.

If you want to use the TabBar/NavigatorIOS integration or use getImageSource, then you need to add RNVectorIcons.xcodeproj to Libraries and add libRNVectorIcons.a to Link Binary With Libraries under Build Phases. More info and screenshots about how to do this is available in the React Native documentation.

**Comment by kmcgill88** [comment]
I have this same issue and it still wasn't working. Finally I opened Xcode and realized after running the `react-native link react-native-vector-icons` command didn't quite link correctly under `Build Phases`. All I did was open the `Libraries` group on the left panel and clicked and drug the `libRNVectorIcons.a` back into build phases and removed the old one. Last I had to clean the Xcode build `Product -> Clean` and then again (holding option) `Product -> Clean`. Last build Xcode again. Refreshed RN app and was good to go. I wasted hours on this!

**Comment by YYEleven** [comment]
read https://www.npmjs.com/package/react-native-vector-icons can resolve the problem

**Comment by RafaRuiz** [comment]
I had to remove `libRNVectorIcons` from Build Phases and re-add it

**Comment by hoanganhbk94** [comment]
@kmcgill88 Thanks :))

**Comment by thinkbed** [comment]
I fix this problem by running "reac-native link" command follow the instruction of https://www.npmjs.com/package/react-native-vector-icons.

**Comment by kwes01** [comment]
i have this error

![imagen](https://user-images.githubusercontent.com/17342168/33218981-1c7450bc-d0fd-11e7-968e-cf6d7c4dec22.png)

**Comment by xavier-villelegier** [comment]
@kwes01 This was quickly fixed in the `v0.18.4`, please update your RNE

**Comment by binora** [comment]
Hi, I use expo and have preloaded the fonts as per documentation but i still get this error : 
![screen shot 2017-11-26 at 1 09 35 pm](https://user-images.githubusercontent.com/6769982/33237323-36c4aa5c-d2ab-11e7-9d73-315b863aac5f.png)

versions : 
"react-native-elements": "^0.18.4"
"expo": "^23.0.0"

It works on Android but not on IOS. Please help

**Comment by hoangvuanhdevelopervn** [comment]
You have to link to library: react-native link react-native-vector-icons
