### ISSUE TITLE
Raised button causing error: View #928 of type RCTView has a shadow set but cannot calculate shadow efficiently. 

### ISSUE THREAD

**Issue by JLLLinn** [react-native-training/react-native-elements#550]
### Description

I added a button with 'raised' specified.

I got this error:
"ADVICE) View #928 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component."

My version is 0.15.0 of react native elements. And as you can see from the code, I do set the background color of the underlay view.

Sample code:
```
<View
        style={{
          flex: 1,
          flexDirection: 'column',
          backgroundColor: 'grey',
        }}
      >
        <Button
          raised
          icon={{ name: 'translate' }}
          title={'Stuff'}

          backgroundColor={colorStyles.allMaterialColors.lightBlue.shade_500}
          containerViewStyle={{ marginTop: 10 }}
        />
</View>
```

**Comment by Monte9** [comment]
@JLLLinn thanks for the issue. Can you please recreate this issue with a [Snack](https://snack.expo.io/) demo? One of use can help you debug this issue. thanks.

**Comment by xavier-villelegier** [comment]
@JLLLinn The sample you gave doesn't throw any error on [this snack demo](https://snack.expo.io/SJq0q6rO-), can you give us a little bit more context ?
Just in case, have you tried with RNE 0.16 ?

**Comment by JLLLinn** [comment]
Hello, thanks for the reply.
Please go ahead and close this since I do not have time to do repro now.

**Comment by DonkeyTronKilla** [comment]
I am having the same problem and i've tracked it down to some difference in building and running using react-native init and using expo. The warning is only shown when building and running from native apps (using react-native init/run-ios). The following simple example works for me in expo without errors but throws the error reported in the original issue above. Can we re-open this or should I be creating a new issue?

```
import React, { Component } from "react";
import { View } from "react-native";
import { Button } from "react-native-elements";

export default class App extends Component {
    render() {
        return (
            <View style={containerStyle}>
                <Button title={"hi"} raised />
            </View>
        );
    }
}

const containerStyle = {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#03A9F4"
};

```

**Comment by Monte9** [comment]
@DonkeyTronKilla thanks for the detailed explanation and code sample. I'll reopen this as it def seems to be a bug since it's causing an error with `react native init`. Let's try to fix this for the `v0.18` release in the next week or so.

**Comment by iRoachie** [comment]
Should be fixed in the next release

**Comment by Monte9** [comment]
Thanks for the fix @iRoachie! 💯

**Comment by iRoachie** [comment]
Fixed in v18.0.0

**Comment by cosmocoder** [comment]
This issue is still happening with version 0.19.0. Setting a backgroundColor in `containerViewStyle` fixes the issues (it doesn't matter what colour you set as long as there is already a backgroundColour set in `buttonStyle`

**Comment by Monte9** [comment]
@cosmocoder I would highly suggest you upgrade to `v1.0.0-beta` and try it out. 

There are lot of new features & we are actively maintaining it. If you face this issue on `v1`, we will be more than happy to address it asap.

Just do: `yarn add react-native-elements@beta`
