### ISSUE TITLE
Problem with Card style

### ISSUE THREAD

**Issue by rainbowhat** [react-native-training/react-native-elements#636]
<Card
			  title={item.title}
			  imageStyle = {{}}
			  image={{uri: 'IMAGE URL HERE'}}>
			 
			</Card>

The picture is darker. It seems like something dark is covering it , the original images source is bright. Once i add it into Card's image , it's darker now

**Comment by xavier-villelegier** [comment]
Thank's for reporting this @rainbowhat  ! The fix should be in the next release. 👌

**Comment by iRoachie** [comment]
Fixed in v18.0.0

**Comment by adisojeda** [comment]
Hello, I am using react-native-elements version 0.18.5 and I am still getting the dark overlay over my images in Card, regardless of if they have a title and subtitle or not;
my code:

` <Card
        key={card.objectId}
        containerStyle={{borderRadius: 10, width: SCREEN_WIDTH * 0.92, height: SCREEN_HEIGHT - 165,  marginTop: 20}}
        featuredTitle={card.objectId >0 ?`${weekday}, ${month} ${day}`: " "}
        featuredTitleStyle={{position: 'absolute', left: 15, top: 10, fontFamily: "Arial", fontWeight: "100",fontSize: 25 }}
        
        featuredSubtitle={`${card.title}`}
        featuredSubtitleStyle={{position: 'absolute', left: 15, bottom: 10, fontFamily: "Arial", fontWeight: "100",fontSize: 22 }}
        image={{ uri: card.imageUri }}
        imageStyle={{borderRadius: 10, width: SCREEN_WIDTH * 0.915, height: SCREEN_HEIGHT - 305}}
      >`

I am using Expo if that matters.

**Comment by Monte9** [comment]
@adisojeda kindly open a new issue and we can try to help you resolve your issue. Also adding a screenshot of what you are seeing would help a lot.
